### ISSUE TITLE
Removing integrated addresses and payment id options

### ISSUE THREAD

**Issue by abhishek1104** [wownero/wownero#102]
Hi,

Since current version already supports Subaddress and Accounts,so why not to make the use of integrated addresses and payment ids obsolute.

Also since Wownero is quite young now,it should not be a blocker for Exchanges (As it's currently on no big exchange -- If this is what is holding back for doing it).

I think it would be great to consider this thing....(Irrespective of Monero still using it)

**Comment by SamsungGalaxyPlayer** [comment]
Ref: https://github.com/monero-project/monero/issues/3772
