### ISSUE TITLE
Logo change discussion -- why no more 🐕

### ISSUE THREAD

**Issue by abhishek1104** [wownero/wownero#103]
Why not remove to doge pic in the logo,and decide a pic which may more better suit wow..

**Comment by jwinterm** [comment]
The actual logo that exchanges use is just a rotated Monero logo. The doge
is just for wow. What would you suggest anyway? Wowario? That might result
in cease and desist from Nintendo.

**Comment by abhishek1104** [comment]
Hmm..That was interesting (W).
So is it official logo or yet not decided any logo.

But again Wownero = Wow + Monero (Currency)

(2nd part need a bit thought I guess as we are not exactly as Monero -- like no tail emission,more rings,more privacy)...

Why not wowcash.As nothing is as private as CASH...And Wowcash -- better cash.


Why can't we make W as the logo of the coin.For simplicity and it will also look great.

**Comment by wowario** [comment]
Meta repo would be a better place for this issue. @abhishek1104  could you close this issue and open it here https://github.com/wownero/meta/issues

**Comment by abhishek1104** [comment]
Agree.. Closing here

**Comment by abhishek1104** [comment]
Agree.. Closing here
