### ISSUE TITLE
New PoW for v0.5

### ISSUE THREAD

**Issue by wowario** [wownero/wownero#145]
Wownero will fork to a new PoW soon™ A [testnet](http://explorer.wowne.ro:8082) and [pool](https://testnet.wowne.ro) has been setup.

Miners
- [xmrig](https://github.com/SChernykh/xmrig/tree/CryptonightR)
- [xmrig-amd](https://github.com/SChernykh/xmrig-amd/tree/CryptonightR)
- [xmrig-nvidia](https://github.com/SChernykh/xmrig-nvidia/tree/CryptonightR)

Please test your rig performance compared to CN/2 and post results [here](https://github.com/SChernykh/CryptonightR/issues/2).

**Comment by SChernykh** [comment]
1-2% hashrate drop is normal because CPU/GPU miner code is not fully optimized yet. In case there is a significant hashrate drop on some hardware, we have an option to reduce random math size appropriately.

**Comment by Gingeropolous** [comment]
holy shit you guys are doing it!!!!!!!!!!!!!!!!!!!!

**Comment by SChernykh** [comment]
@wowario 
Testing shows that hashrate fluctuations on some CPUs are big, so I'll change code generator next week to fix this. It means reference hash vectors will change and testnet reset will be needed.

**Comment by wowario** [comment]
@SChernykh no problem. We can reset it anytime.

**Comment by SChernykh** [comment]
I've started updating code generator in various repositories, please don't test anything now. Second round will start next week and it will require testnet reset and pool update.

**Comment by wowario** [comment]
testing complete
