### ISSUE TITLE
[PROPOSAL] Auto-churn option in CLI wallet

### ISSUE THREAD

**Issue by wowario** [wownero/wownero#146]
Idea from https://github.com/monero-project/monero/issues/4305

Have an option in the CLI wallet where a user is able to type `churn` in wallet and runs a churning process automatically N times. Purportedly, churning helps increase the number of possible outputs for ring signatures.

Help wanted... If you are game for coding this, hop on to freenode IRC #wownero

**Comment by SamsungGalaxyPlayer** [comment]
You're on your own for the coding, but a churning feature should have the following options:

1. Number of churns. How many times should the configuration set in #2 occur?

2. Type of churn. Should the tool churn the entire wallet balance (e), each subaddress balance (s), or each output independently (o)? Default each subaddress.

3. Spend distribution. Should default to a sensible distribution, but should allow users to manually specify the desired spend periods.

4. Proper warnings when using churning for "dumb" behavior. Example includes attempting to churn while connected to a remote node (though can bypass for their own-controlled remote node).

Example syntax:

`churn 1` sends one transaction for all funds in a subaddress to the same subaddress. Transaction takes multiple inputs in the first transaction for all inputs sent to the subaddress. Defaults to a normal spend distribution (approx. 2 days/tx).

`churn 5 o` sends 5 transactions for all outputs independently to the same subaddresses they were received at. Defaults to a normal spend distribution (approx. 2 days/tx).

`churn 3 e 0.5` sends 3 transactions, beginning with the first transaction sending the entire balance of the account with multiple inputs, to the main address (4...). Sends these three transactions within 0.5 days, with each transaction approximately spaced out over this time period with some variance.

---

Feel free to choose a better syntax, but this is my initial thought process given my recommended requirements.

**Comment by wowario** [comment]
@jwinterm yes, I think so.
