### ISSUE TITLE
Compile failed in Ubuntu 16

### ISSUE THREAD

**Issue by KhmerRun** [wownero/wownero#18]
Hi I got these error with make -j2

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libboost_filesystem.a(operations.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libboost_filesystem.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/blockchain_utilities/CMakeFiles/blockchain_export.dir/build.make:185: recipe for target 'bin/wownero-blockchain-export' failed
make[3]: *** [bin/wownero-blockchain-export] Error 1
make[3]: Leaving directory '/home/lolalola/daemon-wownero/wownero-20180424/build/release'
CMakeFiles/Makefile2:3205: recipe for target 'src/blockchain_utilities/CMakeFiles/blockchain_export.dir/all' failed
make[2]: *** [src/blockchain_utilities/CMakeFiles/blockchain_export.dir/all] Error 2
make[2]: Leaving directory '/home/lolalola/daemon-wownero/wownero-20180424/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/lolalola/daemon-wownero/wownero-20180424/build/release'
Makefile:57: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by jwinterm** [comment]
Looks like it is complaining about boost not being compiled with -fPIC
flag. Did you just install boost from ubuntu repositories?

**Comment by KhmerRun** [comment]
Hi,

I installed it via apt.

libboost-dev/xenial,now 1.58.0.1ubuntu1 amd64 [installed,automatic]
  Boost C++ Libraries development files (default version)

The other crypto had no issue compiling with this version of boost.

Regards,

**Comment by wowario** [comment]
Try this:
- `git clone https://github.com/wownero/wownero`
- `cd wownero && git fetch && git checkout release-v0.2.1.0`
- `git submodule init && git submodule update`
- `make`

**Comment by wowario** [comment]
[Release-v0.2.1.0](https://github.com/wownero/wownero/tree/release-v0.2.1.0) compiles on Ubuntu 16.04 clean install once required [dependencies](https://github.com/wownero/wownero/tree/release-v0.2.1.0#dependencies) are installed.
