### ISSUE TITLE
increase mandatory ringsize in next hardfork

### ISSUE THREAD

**Issue by wowario** [wownero/wownero#2]
Many, many more rings! My vote is for static ringsize 69.

**Discussions**: https://github.com/monero-project/monero/issues/1673, https://github.com/monero-project/monero/issues/3035, https://github.com/monero-project/monero/issues/3069

@SamsungGalaxyPlayer's [Excel document with the data and calculations](https://onedrive.live.com/view.aspx?resid=473062B43FF0AD33!23780&ithint=file%2cxlsx&app=Excel&authkey=!AOpTq2h4tkFKeUU)

**Comment by SamsungGalaxyPlayer** [comment]
Bumping the ringsize to 69 increases the pre-bulletproof transaction size by about 63% and increases the verification time by about 230%.

Take the data on churning with salt. It's an ongoing area of research.

![ringsize 7 1](https://user-images.githubusercontent.com/12520755/38821442-21acdac0-4166-11e8-966a-ef0474acb0b8.PNG)
![ringsize 69 1](https://user-images.githubusercontent.com/12520755/38821443-21bef6b0-4166-11e8-8f4d-a5896da68415.PNG)
![ringsize 69 2](https://user-images.githubusercontent.com/12520755/38821444-21ce32ba-4166-11e8-8361-e5b6472acadd.PNG)

**Comment by wowario** [comment]
@SamsungGalaxyPlayer we are thinking about increasing the ringsize when we fork to v8. I've taken a look at @knaccc's javascript code. Is there an estimate of what range proof sizes and EC mult counts for bulletproof verifications might be?

**Comment by SamsungGalaxyPlayer** [comment]
@wowario I'm looking at the bulletproof data now. I'll check back here when I have more data.
