### ISSUE TITLE
New error in wallet for v0.6.1

### ISSUE THREAD

**Issue by fuwa0529** [wownero/wownero#210]
In a test wallet, some outputs can't be spent.

wallet error:

```
Error: internal error: Known ring does not include the spent output: 628974
```

https://paste.debian.net/1086611/

**Comment by wowario** [comment]
From my repo, try `git fetch --all && git checkout testnet` and `make`. This branch has the latest commits. Also delete `.shared-ringdb` folder before starting a new wallet.

**Comment by fuwa0529** [comment]
In log-level 1, right before the error

```
Ring has output 628974
Ignoring output 628974, too recent
!own_found. THROW EXCEPTION: error::wallet_internal_error
```

**Comment by fuwa0529** [comment]
v0.6.0.0 also has this error, v0.5.1.0 is fine. I'll check the testnet branch tomorrow.

**Comment by wowario** [comment]
I've seen a [similar error](https://github.com/wowario/wownero/issues/1) before. Try deleting `.shared-ringdb` folder and create a new wallet from seed.

**Comment by fuwa0529** [comment]
Deleting `.shared-ringdb` and restoring from seed didn't work for me on v0.6.1.

**Comment by fuwa0529** [comment]
@wowario testnet branch didn't fix it neither (deleted `.shared-ringdb` and restored wallet). Guess I'll just stick with the wow classic.

**Comment by fuwa0529** [comment]
Preparing a PR for the fix
