### ISSUE TITLE
wownero can't get tx hash 58942596de699235ca60882b9378955267db0fe5ffd3f25dd2faadd1d7953c3b on block explorer 

### ISSUE THREAD

**Issue by amittalele** [wownero/wownero#218]
i am mining wownero from yesterday from cryptonight.cc pool it is showing payment as
below transaction

fb4652aac03959a822c927057f3155105fe07af4ee93a73507c496abb89fa485

32ba1cbe9b51b46f7cbc24b295e1ee6b8f7900dc0286da1ff46d99269a821258

58942596de699235ca60882b9378955267db0fe5ffd3f25dd2faadd1d7953c3b

but non are showing on block explorer why
--

**Comment by wowario** [comment]
You got screwed over by [Seb Green](https://twitter.com/sebseb7). Wownero forked last week and cryptonight.cc pool never updated, so they have been mining a dead chain.
