### ISSUE TITLE
GUI wallet crashes on initial setup at the "create password" prompt

### ISSUE THREAD

**Issue by itiswow** [wownero/wownero#23]
From wow gui logs

2018-05-04 01:41:14.518	2176	INFO 	logging	contrib/epee/src/mlog.cpp:185	New log categories: *:WARNING,net:FATAL,net.p2p:FATAL,net.cn:FATAL,global:INFO,verify:FATAL,stacktrace:INFO,logging:INFO,msgwriter:INFO
2018-05-04 01:41:18.770	2176	WARN 	net.http	src/common/util.cpp:627	Failed to determine whether address '' is local, assuming not
2018-05-04 01:41:30.612	2176	ERROR	net.http	src/wallet/node_rpc_proxy.cpp:98	Failed to connect to daemon

From windows logs
1.
Faulting application name: wownero-wallet-gui.exe, version: 0.0.0.0, time stamp: 0x5adbcdc7
Faulting module name: libssp-0.dll, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc000001d
Fault offset: 0x00001655
Faulting process id: 0x1228
Faulting application start time: 0x01d3e348fbee65e1
Faulting application path: ***\***\wownero-gui-win-busty-brazzers\wownero wallet\wownero-wallet-gui.exe
Faulting module path: ***\***\wownero-gui-win-busty-brazzers\wownero wallet\libssp-0.dll

EventData 

   wownero-wallet-gui.exe 
   0.0.0.0 
   5adbcdc7 
   libssp-0.dll 
   0.0.0.0 
   00000000 
   c000001d 
   00001655 
   1228 
   01d3e348fbee65e1 
   \wownero-gui-win-busty-brazzers\wownero wallet\wownero-wallet-gui.exe 
   \wownero-gui-win-busty-brazzers\wownero wallet\libssp-0.dll 

2.
Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, 
the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. 
Windows closed the program wownero-wallet-gui.exe because of this error.

EventData 
    
   wownero-wallet-gui.exe 
   68CC1655 
   0

**Comment by wowario** [comment]
please close and move issue to https://github.com/wownero/wownero-gui/issues
