### ISSUE TITLE
allocLargePagesMemory error (stacktrace) on Raspbian 4.19.97 armv7l

### ISSUE THREAD

**Issue by danyelizondo** [wownero/wownero#233]
Hi,
Just compiled Wownero on a Raspberry Pi 2B (Cortex A7) with Raspbian Buster Lite (4.19.97-v7+). The goal is to setup as a public node. It works apparently OK, but when installed as a systemd service, the log file (with _stderror_) shows the following issues, over and over again: 

`604fe010	INFO	stacktrace	src/common/stack_trace.cpp:172	    [1]  0xd4) [0x694794]:__cxa_throw+0xd4) [0x694794]`

`604fe010	INFO	stacktrace	src/common/stack_trace.cpp:172	    [2]  0x74) [0xbb80f4]:_Z21allocLargePagesMemoryj+0x74) [0xbb80f4]`

`604fe010	INFO	stacktrace	src/common/stack_trace.cpp:172	    [3]  0x24) [0xbae8c8]:_ZN7randomx6VmBaseINS_18LargePageAllocatorELb1EE8allocateEv+0x24) [0xbae8c8]`

`604fe010	INFO	stacktrace	src/common/stack_trace.cpp:172	    [4]  0x148) [0xbac1fc]:_create_vm+0x148) [0xbac1fc]`

Seems like a problem with the allocation of the Larges Pages (or Huge Pages). As the armv7l architecture doesn't have, is there any way to stop this, or perhaps it is another problem? The synchronization works OK, I set-up threads_mining as 0 (just to be sure it is not mining).
Thanks in advance,
Daniel E.

**Comment by jwinterm** [comment]
I asked on IRC for you:  

> <jwinterm> is there a way to compile or run monerod without huge pages/huge page support?
> <jwinterm> https://github.com/wownero/wownero/issues/233
> <moneromooo> It's not fatal, it goes on to allocate "normally".
> <gingeropolous> jwinterm, there should be... thats sorta the point of the "lite" mode for randomx. im guessing it tries to run it big and then defaults to lite mode
> <moneromooo> If it's the spam that's the problem, I think yo need to renmove the first alloc call.
> <jwinterm> I think it's the spam that's the problem
> <gingeropolous> those INFO messages
> <jwinterm> .shrug
> <moneromooo> Line 225 in rx-slow-hash.c
> <gingeropolous> ima make tshirts. INFO WARN ERROR
> <moneromooo> cache = randomx_alloc_cache(flags | RANDOMX_FLAG_LARGE_PAGES);
> <moneromooo> Skipping that should do it.
> <asymptotically> wasn't there an environment variable to control it?
> <gingeropolous> i thought there was too, but i just scanned the help and didn't find a flag
> <gingeropolous> oh you mean export=something do magic
> <jwinterm> yea I looked at monerod help and didn't see option
> <jwinterm> set variable before compile?
> <gingeropolous> .dunno

So, you can just ignore it, because they're just INFO messages, or you can remove the alloc call on line 225 in rx-slow-hash.c before compiling it looks like.

**Comment by danyelizondo** [comment]
Great! Good to know that. I will recompile and if SPAM is gone, I'll close the issue.
Thank you very much!
