### ISSUE TITLE
Boost 1.73 build issues

### ISSUE THREAD

**Issue by 420coupe** [wownero/wownero#263]
Ubuntu 16.04 
Attempting to build from master, below is the output. 

I tried applying xmr commit 6613 with no success still the same error results at the end. 

https://pastebin.com/XDRLsJJU

**Comment by wowario** [comment]
you need to have openssl v1.1.1 installed

**Comment by 420coupe** [comment]
worked with openssl v1.1.1 but had all the boost warnings that assuming require the 6612 port
