### ISSUE TITLE
building from source fails on sha3.c

### ISSUE THREAD

**Issue by qvqc** [wownero/wownero#265]
trying to setup deterministic builds, what am I missing here?  it looks like its failing on sha3.c  

[ 95%] Linking CXX executable ../../bin/wownero-wallet-cli
../crypto/libcncrypto.a(sha3.c.o): In function `sha3':
sha3.c:(.text+0x36): undefined reference to `EVP_MD_CTX_new'
sha3.c:(.text+0x46): undefined reference to `EVP_sha3_256'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/wownero-wallet-cli] Error 1
src/simplewallet/CMakeFiles/simplewallet.dir/build.make:144: recipe for target 'bin/wownero-wallet-cli' failed
CMakeFiles/Makefile2:3243: recipe for target 'src/simplewallet/CMakeFiles/simplewallet.dir/all' failed
make[1]: *** [src/simplewallet/CMakeFiles/simplewallet.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 96%] Linking CXX executable ../../bin/wownero-wallet-rpc
../crypto/libcncrypto.a(sha3.c.o): In function `sha3':
sha3.c:(.text+0x36): undefined reference to `EVP_MD_CTX_new'
sha3.c:(.text+0x46): undefined reference to `EVP_sha3_256'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/wownero-wallet-rpc] Error 1
src/wallet/CMakeFiles/wallet_rpc_server.dir/build.make:144: recipe for target 'bin/wownero-wallet-rpc' failed
make[1]: *** [src/wallet/CMakeFiles/wallet_rpc_server.dir/all] Error 2
CMakeFiles/Makefile2:2771: recipe for target 'src/wallet/CMakeFiles/wallet_rpc_server.dir/all' failed
make: *** [all] Error 2
Makefile:140: recipe for target 'all' failed

**Comment by wowario** [comment]
you need to have openssl v1.1.1 installed

**Comment by fuwa0529** [comment]
forced update is real

**Comment by qvqc** [comment]
I tried compiling with libssl-dev added in gitian-linux packages.   Also with changed it to build all for open ssl in that dockerfile (https://github.com/wownero/wownero/blob/master/Dockerfile#L55-L67).  Both fail with the same error.  What am I missing?

**Comment by enerc** [comment]
Same issue when building the arm8 binaries for wownerod on android.
I have set OPENSSL_ROOT_DIR to a 1.1.1 folder. 
The android NDK linker says:
/opt/android/wownero/src/crypto/sha3.c:(.text+0x38): undefined reference to `EVP_MD_CTX_new'
/opt/android/wownero/src/crypto/sha3.c:(.text+0x44): undefined reference to `EVP_sha3_256'

(what's strange is that the link was using /usr/lib, thus x86-64 - I had to change it in src/daemon/CMakeFiles/daemon.dir/link.txt)

**Comment by fuwa0529** [comment]
For android, you can let fdroid server build it: 

https://gitlab.com/fdroid/fdroiddata/-/raw/master/metadata/org.wownero.cyberwow.yml

Or just use the binary built by f-droid, rename the apk to zip and unzip, search for `libwownerod.so`, and rename it to `wownerod`.

https://f-droid.org/en/packages/org.wownero.cyberwow/

**Comment by enerc** [comment]
Thanks for the build Fuwa!. I have updated https://github.com/enerc/wownero-daemon

**Comment by wowario** [comment]
@qvqc is this issue resolved?

**Comment by qvqc** [comment]
I will close for now and reopen if I test with sha3 again.
