### ISSUE TITLE
deterministic build fails win64 makin qvqc cry

### ISSUE THREAD

**Issue by qvqc** [wownero/wownero#267]
why build fails?    same happens on risc64

`
WIN64 BUILD:
 
[ 25%] Building C object src/crypto/CMakeFiles/obj_cncrypto.dir/slow-hash.c.obj
/home/ubuntu/build/wownero/src/crypto/slow-hash.c:1630:6: error: redefinition of ‘slow_hash_allocate_state’
 void slow_hash_allocate_state(void)
      ^~~~~~~~~~~~~~~~~~~~~~~~
/home/ubuntu/build/wownero/src/crypto/slow-hash.c:1446:6: note: previous definition of ‘slow_hash_allocate_state’ was here
 void slow_hash_allocate_state(void)
      ^~~~~~~~~~~~~~~~~~~~~~~~
/home/ubuntu/build/wownero/src/crypto/slow-hash.c: In function ‘slow_hash_allocate_state’:
/home/ubuntu/build/wownero/src/crypto/slow-hash.c:1632:3: warning: implicit declaration of function ‘cn_slow_hash_allocate_state’; did you mean ‘rx_slow_hash_allocate_state’? [-Wimplicit-function-declaration]
   cn_slow_hash_allocate_state();
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
   rx_slow_hash_allocate_state
/home/ubuntu/build/wownero/src/crypto/slow-hash.c:1632:3: warning: nested extern declaration of ‘cn_slow_hash_allocate_state’ [-Wnested-externs]
src/crypto/CMakeFiles/obj_cncrypto.dir/build.make:513: recipe for target 'src/crypto/CMakeFiles/obj_cncrypto.dir/slow-hash.c.obj' failed
make[2]: *** [src/crypto/CMakeFiles/obj_cncrypto.dir/slow-hash.c.obj] Error 1
CMakeFiles/Makefile2:975: recipe for target 'src/crypto/CMakeFiles/obj_cncrypto.dir/all' failed
make[1]: *** [src/crypto/CMakeFiles/obj_cncrypto.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 25%] Building C object external/unbound/CMakeFiles/unbound.dir/util/net_help.c.obj
`

**Comment by qvqc** [comment]
how to reproduce: https://gist.github.com/qvqc/4fe83162c927feb7b40c6519cc87cfd3

**Comment by wowario** [comment]
migrated to https://git.wownero.com/wownero/wownero
