### ISSUE TITLE
Syncing with --sync-pruned-blocks fails

### ISSUE THREAD

**Issue by 00-matt** [wownero/wownero#275]
Log gets spammed with `E get_pruned_transaction_weight does not support older range proof types` after height ~6900.

To reproduce, sync from scratch with `--prune-blockchain --sync-pruned-blocks` args.

**Comment by wowario** [comment]
appears to be the same issue reported in https://github.com/monero-project/monero/issues/6498

wownero has https://github.com/monero-project/monero/pull/6503 commit

**Comment by 00-matt** [comment]
weird, this happened in the 0.8.0.0 tagged release for me which contains that commit

**Comment by wowario** [comment]
migrated to https://git.wownero.com/wownero/wownero
