### ISSUE TITLE
wownero-gui on ubuntu 16.04 (x64) : "QtQuick.Controls" version 2.0 is not installed

### ISSUE THREAD

**Issue by cryptozeny** [wownero/wownero#4]
Hi wow devs,

wownero and wownero-gui build ok. but i got error when i run it.

> ~/git/MONERO/wownero-gui$ ./build/release/bin/wownero-wallet-gui 
> 
> (wownero-wallet-gui:1677): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
> app startd
> available width:  1855
> available height:  1056
> devicePixelRatio:  1
> screen height:  1920
> screen width:  1080
> screen logical dpi:  96
> screen Physical dpi:  157.74
> screen calculated ratio:  1.23235
> QQmlApplicationEngine failed to load component
> qrc:///main.qml:1044 Type StandardDialog unavailable
> qrc:///components/StandardDialog.qml:30 module "QtQuick.Controls" version 2.0 is not installed
> 
> Error: no root objects

Ubuntu 16.04.4 LTS x64

> $ sudo apt qml-module-qtquick-controls2
> E: Invalid operation qml-module-qtquick-controls2

Any suggest? Why there is no ISSUE tab on wownero-gui repo?

I googled about this issue, but still no answer there.

https://github.com/monero-project/monero-gui/issues/1242

https://www.google.co.kr/search?q=%22qrc%3A%2F%2F%2Fcomponents%2FStandardDialog.qml%3A30+module+%22QtQuick.Controls%22+version+2.0+is+not+installed%22&oq=%22qrc%3A%2F%2F%2Fcomponents%2FStandardDialog.qml%3A30+module+%22QtQuick.Controls%22+version+2.0+is+not+installed%22&aqs=chrome..69i57.1191j0j1&sourceid=chrome&ie=UTF-8

Many thanks

**Comment by wowario** [comment]
You might need to install the missing package manually. You can find the `qml-module-qtquick-controls2` package here: https://packages.ubuntu.com/artful/amd64/qml-module-qtquick-controls2/download

**Comment by wowario** [comment]
@cryptozeny try this: https://stackoverflow.com/questions/45509760/ubuntu-qt-install-qt-quick-controls-2-1

**Comment by bomb-on** [comment]
@cryptozeny You're trying to install wrong package... For Ubuntu 16.04 install `qml-module-qtquick-controls`:

`sudo apt install qml-module-qtquick-controls`

**Comment by cryptozeny** [comment]
@bomb-on 

i have already installed it, but it still ask the package... I am on ubuntu 16.04.4 x64

***

> wownero-gui$ sudo apt install qml-module-qtquick-controls
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> **qml-module-qtquick-controls is already the newest version (5.5.1-1ubuntu1).**
> 0 upgraded, 0 newly installed, 0 to remove and 79 not upgraded.

***

> wownero-gui$ ./build/release/bin/wownero-wallet-gui
> (wownero-wallet-gui:1990): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
> app startd
> available width:  1855
> available height:  1056
> devicePixelRatio:  1
> screen height:  1920
> screen width:  1080
> screen logical dpi:  96
> screen Physical dpi:  157.74
> screen calculated ratio:  1.23235
> QQmlApplicationEngine failed to load component
> qrc:///main.qml:1206 Type NewPasswordDialog unavailable
> **qrc:///components/NewPasswordDialog.qml:29 module "QtQuick" version 2.7 is not installed**
> 
> Error: no root objects

Any idea?

**Comment by bomb-on** [comment]
Did you try to install other qt plugins maybe?

`sudo apt install qtbase5-dev qt5-default qtdeclarative5-dev qml-module-qtquick-controls qml-module-qtquick-xmllistmodel qttools5-dev-tools qml-module-qtquick-dialogs qml-module-qt-labs-settings libqt5qml-graphicaleffects qtmultimedia5-dev qml-module-qtmultimedia libzbar-dev`

I also enabled issues on wownero-gui repo, if this won't help, please reopen this issue there!

**Comment by cryptozeny** [comment]
i already installed.all of them, and it won't run... i reopened this issue there

**Comment by Ravendocker** [comment]
so how to solve this？ in Ubuntu16.04，Qt version 5.91，this problem exists too.

QT_XCB_GL_INTEGRATION:  "xcb_glx"
event dispatcher: 0x1024ad0
set log file:  "/home/niuniu/viper/build/log-Viper.txt"
Logger
Debug: arguments=======  ("./viper")
Debug: current dir:  "/home/niuniu/viper/build"
Debug: ("/home/niuniu/viper/build", "/usr/lib/x86_64-linux-gnu/qt5/qml")
Debug: >>>>>>>>devicePixelRatio: 1.000000
Debug: dpi phy:  71.2433 , logical:  96 , dpr:  1 ; vis rect: QRect(0,0 1916x927)
Debug: touch devices:  ()
Warning: qrc:///qml/Viper/main.qml:719:5: Type OptionConnections unavailable
Warning: qrc:///qml/Viper/OptionConnections.qml:19:1: module "QtQuick.Controls" version 2.0 is not installed
Debug: file:  ""
Warning: QObject::connect: Cannot connect (null)::requestFullScreen() to QtQuick2ApplicationViewer::showFullScreen()
Warning: QObject::connect: Cannot connect (null)::requestNormalSize() to QtQuick2ApplicationViewer::showNormal()
Segmentation fault (core dumped)
