### ISSUE TITLE
get_spend_proof Error: failed to parse tx from blob

### ISSUE THREAD

**Issue by itssteven** [wownero/wownero#40]
Everything was okay with the original commit, but after rebuilding I get this error when trying to get_spend_proof. I've tried 'reinstalling' everything to no avail.

**Comment by wowario** [comment]
Have you tried checking out the `release-v0.2.1.0` branch and creating a new wallet from seed?

**Comment by stoffu** [comment]
That's due to the daemon RPC command `/gettransactions` being called with `req.prune = true`. All the occurrences of it in wallet2.cpp should be replaced by `req.prune = false`, which is the case with Monero (pending https://github.com/monero-project/monero/pull/3890).

**Comment by itssteven** [comment]
I didn't realise I had to `git clone --recursive -b release-v0.2.1.0 https://github.com/wownero/wownero.git
`

Works now :) Thanks
