### ISSUE TITLE
Make pool

### ISSUE THREAD

**Issue by swa74** [wownero/wownero#5]
Make a pool with another script - https://github.com/dvandal/cryptonote-nodejs-pool? without aes-ni

**Comment by jwinterm** [comment]
It shouldn't matter the pool side, just need to use a miner that works
without aes-ni, right?

**Comment by swa74** [comment]
Совершенно не верно - "multi-hashing" и "cryptonote-util" могут требовать aes-ni

**Comment by swanseahost** [comment]
Is there a config.json anywhere to check coin and targret ?

**Comment by wowario** [comment]
@swanseahost coin details are found here: https://github.com/wownero/wownero/blob/master/src/cryptonote_config.h
