### ISSUE TITLE
compile fails on Mac OSX

### ISSUE THREAD

**Issue by cryptonote-social** [wownero/wownero#61]
Error message: 
[ 14%] Building CXX object contrib/epee/src/CMakeFiles/epee.dir/connection_basic.cpp.o
In file included from /Users/dad/cryptonote/src/wownero/contrib/epee/src/connection_basic.cpp:35:
In file included from /Users/xxxx/cryptonote/src/wownero/contrib/epee/include/net/connection_basic.hpp:63:
/Users/xxxx/cryptonote/src/wownero/contrib/epee/include/syncobj.h:37:10: fatal error: 
      'boost/thread/v2/thread.hpp' file not found
#include <boost/thread/v2/thread.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

---------------

I have verified this fix for Monero worked for me in Wownero:

https://github.com/monero-project/monero/pull/3667

**Comment by wowario** [comment]
That [#include <boost/thread/v2/thread.hpp>](https://github.com/wownero/wownero/blob/1f6760533fcec0d84a6bd68369e0ea26716b01e7/contrib/epee/include/syncobj.h#L37) line appears to be from the Master branch. It has been [fixed](https://github.com/wownero/wownero/blob/7ec6f636068367859b15015c655b1cf1213f492e/contrib/epee/include/syncobj.h#L38) in release-v0.2.1.0. 

Try downloading the [latest pre-release](https://github.com/wownero/wownero/releases/tag/v0.2.1.0) and recompiling again.
